Packer base
Otus-DevOps-2018-09/nemanovich_infra pull request #4
Opened 2018-11-16 15:38 UTC by nemanovich

# Выполнено ДЗ № 5

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Добавлено packer описание для базового образа reddit 
 - Добавлено packer описание для полного образа reddit 
 - Добавлен gcloud скрипт для запуска инстанса виртуальной машины из полного образа

## PR checklist
 - [] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-11-28 12:17 UTC, grim-yawn requested changes
Утекли variables.json + пара небольших замечаний.

2018-11-28 12:17 UTC, WeitBelou commented on packer/variables.json
> +{
Должно было быть в .gitignore

2018-11-28 12:17 UTC, WeitBelou commented on packer/immutable.json
> +			"project_id": "infra-221016",
Переменные не использованы

2018-11-28 12:17 UTC, WeitBelou commented on packer/immutable.json
> +			"destination": "/home/otus/"
А почему бы не копировать сразу в /lib/systemd/system ?

2018-12-01 17:37 UTC, nemanovich commented on packer/immutable.json
> +			"destination": "/home/otus/"
Чтобы можно было добавить в files какой-нибудь еще файл для копирования в целевой инстанс vm и он автоматически не оказался бы в systemd (что может быть неожиданным поведением). Это плохая практика?

2018-12-01 17:57 UTC, nemanovich commented
Fixed

2018-12-03 07:27 UTC, grim-yawn commented on packer/immutable.json
> +			"destination": "/home/otus/"
Да, желательно чтобы было явно видно какие файлы будут перемещаться и куда.

2018-12-13 17:50 UTC, nemanovich commented
Изменен destination, можно проверять

2018-12-28 09:12 UTC, grim-yawn approved these changes

2019-01-02 21:35 UTC, merged